### ISSUE TITLE
Sphinxbase install fails

### ISSUE THREAD

**Issue by AlxndrPsclt** [Martchus/PKGBUILDs#112]
I was trying to install ffmpeg-full which depends on pocketsphinx.

The package sphinxbase 5prealpha-10 seems to have a problem on my machine (i5.5.13-arch2-1linux)

When I try to install it using yay - Suy sphinxbase
I get this error:
```
...
! LaTeX Error: File `newunicodechar.sty' not found.
...
```

Investigating it right now; any input is welcome.

**Comment by AlxndrPsclt** [comment]
This comment might be relevant; I'm not yet fluent enough in the package building process to make it work.
https://aur.archlinux.org/packages/pocketsphinx-git/#comment-737044

**Comment by Martchus** [comment]
It looks similar to the problems reported in the AUR and I suggest to follow the same recommendations than I've given in recent comments there: https://aur.archlinux.org/packages/sphinxbase

And especially when building the ffmpeg-dependency-chain it makes sense to build everything in a clean chroot. These build systems otherwise just take what they can find and you end up having packages depending on more libraries than intended and listed in the package's dependencies.

**Comment by AlxndrPsclt** [comment]
Thanks a lot for the pointer towards chroot; and the discussion on https://aur.archlinux.org/packages/sphinxbase that I previously missed. This approach solved the problem.

Just for reference;
  - I followed the steps to create a [chroot folder](https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_clean_chroot)
  - then built the sphinxbase package that was cached in ~/.cache/yay/sphinxbase/
  -Starting from a clean environnement, everything went well
  - finally I could install the resulting sphinxbase-5prealpha-10-x86_64.pkg.tar.xz package via `pacman -U sphinxbase-5prealpha-10-x86_64.pkg.tar.xz`

Installation of ffmpeg-full worked properly after that.

Thanks again; I will mark this as closed.

**Comment by Martchus** [comment]
No problem. However, I'd generally recommend to build all the package in a clean chroot, not only the ones which would otherwise fail entirely.
