### ISSUE TITLE
Remove ttf-roboto from [ownstuff]

### ISSUE THREAD

**Issue by ohmyarch** [Martchus/PKGBUILDs#13]
https://www.archlinux.org/packages/community/any/ttf-roboto/

**Comment by Martchus** [comment]
The package has already been removed from the database. However, the file is still present because I always keep obsolete packages in the directory to have a way to go back when necessary (like it is possible with the [Arch Linux Archive](https://wiki.archlinux.org/index.php/Arch_Linux_Archive) for the official repositories).

**Comment by ohmyarch** [comment]
There is a problem with ${pkgver}. If community/ttf-roboto has been installed, pacman will upgrade it to ownstuff/ttf-roboto.

**Comment by Martchus** [comment]
This is not the case for me and shouldn't happen because the package has been removed from the database (you updated the database, right?).

So it should only be required to force installing community version once (will be a downgrade). There is nothing I can do to automate it. Only the maintainer of the community package could have increased epoch when changing the version schema.

**Comment by ohmyarch** [comment]
Sorry for that, ttf-roboto that still exist is belong to another unoffical repo. because the original package was installed from your repo so I made a mistake😂.

**Comment by Martchus** [comment]
No problem
