### ISSUE TITLE
syncthingtray installation fails due to missing package

### ISSUE THREAD

**Issue by frazar** [Martchus/PKGBUILDs#136]
The syncthingtray PKGBUILD requires the qtforkawesome package, which does not exist on AUR. 

```
[frazar@hostname ~]$ yay -S syncthingtray
 -> Could not find all required packages:
	qtforkawesome (Wanted by: syncthingtray)
```

**Comment by Martchus** [comment]
The missing package should be there now.

**Comment by Martchus** [comment]
I accidentally rebuilt `qtforkawesome` (without bumping pkgrel) replacing the old package. Maybe you have the old version of the database and try to download the new version of the database? It should work if you update the database before.

**Comment by Martchus** [comment]
Looks like the files database is damaged which had prevented further `repo-add` calls. I'll try to sort it out.

**Comment by Martchus** [comment]
I fixed the files database and re-added qtforkawesome. It works now but again there's a database update required.

**Comment by Annakan** [comment]
Hello

On a fresh Manjaro (arch base) install the AUR packages for syncthingtray fail to build with the following message : 
```
could not satisfy dependencies:
- unable to satisfy dependency 'libqtutilities.so' required by syncthingtray
- unable to satisfy dependency 'libqtforkawesome.so' required by syncthingtray
- unable to satisfy dependency 'libc++utilities.so' required by syncthingtray
``` 
This affects the default, the git, and the qt6 version.

This seems related to forwawesome not building because of libgc++utilities.

It does not feel like a Manjaro specific things.

Thanks a lot for your time and expertise.

**Comment by Martchus** [comment]
This issue was resolved by fixing the database file of my binary repository. Note that using my binary repository on a Manjaro system is not supported.

However, it looks like you wouldn't use my binary repository anyways. That means your issue is unrelated. I suppose you simply forgot to build the packages providing the dependencies it is unable to satisfy. You need to build the following AUR packages in the following order: `c++utilities qtutilities qtforkawesome syncthingtray`
(All other packages should be in the official repositories, at least that would be the case for regular Arch Linux. Note that you need to rebuild the mentioned AUR packages when one dependency from official repositories bumps its soname, e.g. when boost was upgraded.)

**Comment by Annakan** [comment]
Thanks a lot for your very prompt answer,  I was under the wrong assumption that the package manager would build the dependencies and record them, and thus supposed something was wrong one of the packages dependencies declaration.
I will read more about AUR to correct my understanding.
Thanks a lot
