### ISSUE TITLE
Qt6 Multimedia in Binary Repo

### ISSUE THREAD

**Issue by Steveice10** [Martchus/PKGBUILDs#162]
I’m currently trying to update a Docker container for MinGW CI builds to include Qt 6. It uses your binary repository for MinGW packages, and I’ve hit a bit of a roadblock since mingw-w64-qt6-multimedia is not available.

I also saw on the AUR that as of 6.4.0 there are build issues compiling Qt6 Multimedia for MinGW. Before I start exploring other solutions, I wanted to ask if you know whether this is still the case as of 6.5.0, and if not whether this package could be included in the binary repository.

**Comment by Martchus** [comment]
Note that Qt Multimedia has never built for real so it is not actually a bug but a feature request.

Note that the static version likely won't be able have ffmpeg support until the required dependency chain is updated. That supposedly means configuring ffmpeg to use OpenSSL instead of GNU TLS because the latter does not support being built as static library. Possibly other dependencies of ffmpeg are problematic as well and should/need to be disabled.

**Comment by Steveice10** [comment]
> Note that Qt Multimedia has never built for real so it is not actually a bug but a feature request.

Right, apologies for that, it got auto-assigned by the template and I couldn’t figure out how to fix the tags.

> Note that the static version likely won't be able have ffmpeg support until the required dependency chain is updated. That supposedly means configuring ffmpeg to use OpenSSL instead of GNU TLS because the latter does not support being built as static library. Possibly other dependencies of ffmpeg are problematic as well and should/need to be disabled.

We’re dynamically linking to Qt and ffmpeg so if this is just a static limitation we should be fine. Plus we’re only using Multimedia for camera devices.

**Comment by Steveice10** [comment]
The underlying issue seems to be case-sensitivity of Linux filesystems. There's a bunch of header includes that work on Windows presumably because of case-insensitivity, but on Linux they fail unless you change them to all lowercase.

**Comment by Steveice10** [comment]
Opened a pull request: https://github.com/Martchus/PKGBUILDs/pull/163

**Comment by Martchus** [comment]
Your change works.

Note that the case-sensitivity is generally a very old problem. Maybe it is worthwhile to put the workaround into a real patch and also try to submit that upstream. I did that in the past; simple changes like that are usually accepted by upstream. I am going to do that tomorrow or at the weekend unless you want to go ahead with it.

By the way, when I tried it before it was not *just* a casing issue. I suppose back then the problem was that mingw-w64 headers were too old. At first that resulted in builds without any actual backend being built but then it ceased to work as of some version of Qt which moved code from the Windows Media SDK to the overall module. Great that mingw-w64 is now up-to-date enough to build the code using the Windows Media SDK and that backend.

Qt is apparently focusing on the FFmpeg backend - also on Windows. At least https://www.qt.io/blog/qt-6.5-lts-released#qt-multimedia reads like it. That also makes sense because only by bundling FFmpeg (and the other libraries it depends on) one can ensure consistent functionality. So it would make also sense to enable the FFmpeg backend in my packaging; at least for the build using shared libraries. That would be the next step. Fixing the dependency chain of FFmpeg for static builds also something worth looking into although I'm unlikely to do it in the near future (as none of my apps currently need it and it is more work).

**Comment by Martchus** [comment]
I'm going to move the package from my experimental repo to the main one when the regular qt6-* packages are updated to 6.5.0. Not sure when this will happen; normally the maintainer is *really* fast so that's a bit unusual. (Hopefully nothing has happened to him.)

**Comment by Steveice10** [comment]
Closing this out since Qt Multimedia 6.5.0 has been in the repository for a while now, thanks!
