### ISSUE TITLE
mingw-w64-qt5-declarative fails to build

### ISSUE THREAD

**Issue by xantares** [Martchus/PKGBUILDs#17]
hello,
mingw-w64-qt5-declarative still doesnt compile after 35f7599:
```
g++ -Wl,--gc-sections -Wl,-rpath,/usr/i686-w64-mingw32/lib -o ../../bin/qmlmin .obj/main.o -L/usr/lib -L/home/xantares/projects/aur-scripts/mingw-w64-qt5-declarative/src/qtdeclarative-opensource-src-5.8.0/build-i686-w64-mingw32-static/lib /usr/i686-w64-mingw32/lib/libQt5QmlDevTools.so -L/usr/lib /usr/i686-w64-mingw32/lib/libQt5Bootstrap.so -lpthread
g++: error: /usr/i686-w64-mingw32/lib/libQt5QmlDevTools.so: No such file or directory
make[2]: *** [Makefile:102: ../../bin/qmlmin] Error 1
make[2]: Leaving directory '/home/xantares/projects/aur-scripts/mingw-w64-qt5-declarative/src/qtdeclarative-opensource-src-5.8.0/build-i686-w64-mingw32-static/tools/qmlmin'
make[1]: *** [Makefile:45: sub-qmlmin-make_first] Error 2
make[1]: *** Waiting for unfinished jobs.... 
```

**Comment by Martchus** [comment]
When testing it, it only worked because I had the package already installed on the system. That's why I usually test in a clean chroot. Last time I didn't do it so I can reproduce the initial issue which only occurs when regular qt5-base is also installed.

I'll fix it when I have time. But I would recommend you to setup a clean chroot rather than building on your regular system and doing some partial/manual cleanup before.

**Comment by Martchus** [comment]
The following should fix it: https://github.com/Martchus/PKGBUILDs/pull/18

Not tested yet, but maybe you want to try.

**Comment by xantares** [comment]
yes!

**Comment by Martchus** [comment]
Finally :-)
