### ISSUE TITLE
qtforkawesome fails to build due to missing yaml

### ISSUE THREAD

**Issue by ddorn** [Martchus/PKGBUILDs#192]
**Before reporting an issue**, check whether there are pinned/recent comments on
the AUR and whether your request is really in-line with
https://wiki.archlinux.org/title/PKGBUILD. ✅

**For more general discussions and questions** about related topics such as
mingw-w64 packaging in general, feel free to open or join a discussion on
https://github.com/Martchus/PKGBUILDs/discussions. ✅

**Note that I cannot help with AUR helpers.** Please report problems with AUR
helpers to their vendors. ✅

**Note that only Arch Linux is supported.** Packages may not build on other
distributions such as Manjaro. ✅

---

Relevant packages: qtforkawesome

Your modifications to the build environment (e.g. changes in `makepkg.conf`):
None

Question/request or brief description of the problem:
qtforkawesome failed to build with the following error on my machine. Installing perl-yaml allowed it to build. Is it missing the build dependency?

```
-- Build files have been written to: /home/diego/.cache/paru/clone/qtforkawesome/src/qtforkawesome-0.2.1
[2/19] Icon header
FAILED: qtforkawesome/headers/private/icons.h qtforkawesome/headers/private/idmapping.h /home/diego/.cache/paru/clone/qtforkawesome/src/qtforkawesome-0.2.1/qtforkawesome/headers/private/icons.h /home/diego/.cache/paru/clone/qtforkawesome/src/qtforkawesome-0.2.1/qtforkawesome/headers/private/idmapping.h
cd /home/diego/.cache/paru/clone/qtforkawesome/src/qtforkawesome-0.2.1/qtforkawesome && /usr/bin/perl /home/diego/.cache/paru/clone/qtforkawesome/src/qtforkawesome-0.2.1/qtforkawesome/scripts/yaml2enum.pl /home/diego/.cache/paru/clone/qtforkawesome/src/Fork-Awesome-1.2.0/src/icons/icons.yml /home/diego/.cache/paru/clone/qtforkawesome/src/qtforkawesome-0.2.1/qtforkawesome/headers/private/icons.h /home/diego/.cache/paru/clone/qtforkawesome/src/qtforkawesome-0.2.1/qtforkawesome/headers/private/idmapping.h
Unable to locate YAML::XS or YAML: Can't locate YAML.pm in @INC (you may need to install the YAML module) (@INC entries checked: /usr/lib/perl5/5.38/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.38/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.38/core_perl /usr/share/perl5/core_perl) at /home/diego/.cache/paru/clone/qtforkawesome/src/qtforkawesome-0.2.1/qtforkawesome/scripts/yaml2enum.pl line 9.
[3/19] Automatic RCC for qtforkawesome_font.qrc
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'qtforkawesome-0.2.1-1':
```

**Comment by Martchus** [comment]
The Perl module it cannot find is supposed to be provided by https://archlinux.org/packages/extra/x86_64/perl-yaml-libyaml. This package is a make dependency so it should have been installed automatically in your build environment. The command `perl -m 'YAML::XS' -e1` is supposed to return with a 0 exit code in your build environment and not print any errors.

Note that at this point you probably want `qtforkaweseom-qt6` and also otherwise switch to `-qt6` packages.

**Comment by Martchus** [comment]
It is strange that https://archlinux.org/packages/extra/x86_64/perl-yaml-libyaml has no dependency to libyaml. That seems like a bug of that Arch Linux package to me considering libyaml is required by that package - unless libyaml is bundled.

**Comment by Martchus** [comment]
I've just pushed a commit to qtforkawesome for a better error message because right now it just tells us that the non-XS module cannot be located (but that's expected). You could try it by building `qtforkawesome-git` although the output of `perl -m 'YAML::XS' -e1` in your build env is probably sufficient to debug this further.

**Comment by ddorn** [comment]
Thanks for the quick response. To be clear: I did manage to install qtforkawesome (as part of syncthingtray). I just had to install first `perl-yaml`. I'm opening this or others that might want to install it in the future.
Would it make sense to swap `perl-yaml-libyaml` for `perl-yaml`? At least changing this worked for me.

Note that I have no knowledge of the perl ecosystem nor qt.

**Comment by HereInPlainSight** [comment]
Hi there.  I don't know perl, but I know my rebuilding `syncthingtray` was dying and seems to be because [line 8 in yaml2enum.pl](https://github.com/Martchus/qtforkawesome/blob/14403eeb0f992b3984ea29b0f389a813432c0327/qtforkawesome/scripts/yaml2enum.pl#L8) says `::XSS` instead of `::XS`, but that seems like a new issue from your earlier fix.  Just bad timing for me to run into it, but wanted to let you know.

**Comment by Martchus** [comment]
@HereInPlainSight Thanks for letting me know. This was actually only introduced by the recent commit mentioned in https://github.com/Martchus/PKGBUILDs/issues/192#issuecomment-2374450669. I pushed a fix. (I added the additional `S` for testing so I can see whether one would actually get the error message now but forgot to remove it again before making the commit.)
