### ISSUE TITLE
qt5-qtbase loads ssleay32.dll by default instead of openssl

### ISSUE THREAD

**Issue by MartinBriza** [Martchus/PKGBUILDs#24]
I found this bug in Fedora mingw-qt5 packages, I guess you're affected too. There's a simple fix in https://bugzilla.redhat.com/show_bug.cgi?id=1438740 .

**Comment by Martchus** [comment]
The `mingw-w64-openssl` package provided in the AUR only contains `ssleay32.dll` and not `libssl-*.dll`. This is the default behavior. The Fedora package is different because of [mingw32-openssl-1.0.0-beta3-libversion.patch](http://pkgs.fedoraproject.org/cgit/rpms/mingw-openssl.git/tree/mingw32-openssl-1.0.0-beta3-libversion.patch).

Hence I suppose there would be no benefit in changing the order here, too. But thanks for letting me know.

**Comment by MartinBriza** [comment]
Oh, okay - as I said, I wasn't sure about it and thought it'd be worth a
shot. Sorry for not investigating it too deep :)

2017-04-04 18:15 GMT+02:00 Martchus <notifications@github.com>:

**Comment by Martchus** [comment]
No problem - patches from Fedora are often useful.
