### ISSUE TITLE
Debug information for Qt packages

### ISSUE THREAD

**Issue by hipersayanX** [Martchus/PKGBUILDs#27]
Please, if possible, Qt packages must provide libraries with both, release and debug information. It makes impossible to debug any program in Windows without that information.

**Comment by Martchus** [comment]
Just replace the `-release` flag with `-debug-and-release`. I could make the PKGBUILD read an environment variable so you can add eg. `MINGW_QT_DEBUGGING=1` to `/etc/makepkg.conf` to enable debug version. However, I will not add this as default because it will make the package very big.

Note that at least under Linux you do not need a debug build of Qt to debug your own code. I guess the same it true under Windows. So a debug build is only required for debugging Qt itself. But then you usually don't a packaged version and likely want the source code as well.

**Comment by hipersayanX** [comment]
Thanks a lot, compiled qt5-base and it worked! I had to modify [this line](https://github.com/Martchus/PKGBUILDs/blob/master/qt5-base/mingw-w64-dynamic/0009-Fix-linking-against-static-D-Bus.patch#L41) because libdbus-1d.so doesn't exist in dbus package. Changed to this:

    -                        "debug": "-ldbus-1d",
    +                        "debug": "-ldbus-1",

Now I'm trying to compile qt5-declarative with  CONFIG+=debug_and_release, but I get this error:

    g++ -Wl,--no-undefined -Wl,--version-script,QtQmlDevTools.version -shared -Wl,-soname,libQt5QmlDevTools.so.5 -o libQt5QmlDevTools.so.5.8.0 .obj/release/qqmljsast.o .obj/release/qqmljsastvisitor.o .obj/release/qqmljsengine_p.o .obj/release/qqmljsgrammar.o .obj/release/qqmljslexer.o .obj/release/qqmljsparser.o .obj/release/qv4runtime.o .obj/release/qv4string.o .obj/release/qv4value.o .obj/release/qv4compileddata.o .obj/release/qv4compiler.o .obj/release/qv4codegen.o .obj/release/qv4isel_p.o .obj/release/qv4jsir.o .obj/release/qv4ssa.o .obj/release/qqmlirbuilder.o  -L/usr/i686-w64-mingw32/lib -lQt5Bootstrap -lpthread  
    .obj/release/qv4ssa.o: In function `__gnu_cxx::new_allocator<int>::deallocate(int*, unsigned long)':
    /usr/include/c++/6.3.1/ext/new_allocator.h:110: undefined reference to `operator delete(void*)'
    /usr/include/c++/6.3.1/ext/new_allocator.h:110: undefined reference to `operator delete(void*)'
    /usr/include/c++/6.3.1/ext/new_allocator.h:110: undefined reference to `operator delete(void*)'
    /usr/include/c++/6.3.1/ext/new_allocator.h:110: undefined reference to `operator delete(void*)'
    /usr/include/c++/6.3.1/ext/new_allocator.h:110: undefined reference to `operator delete(void*)'
    .obj/release/qv4ssa.o:/usr/include/c++/6.3.1/ext/new_allocator.h:110: more undefined references to `operator delete(void*)' follow
    .obj/release/qv4ssa.o: In function `std::vector<int, std::allocator<int> >::_M_range_check(unsigned long) const':
    /usr/include/c++/6.3.1/bits/stl_vector.h:804: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
    .obj/release/qv4ssa.o: In function `QList<QV4::IR::MoveMapping::Move>::node_destruct(QList<QV4::IR::MoveMapping::Move>::Node*, QList<QV4::IR::MoveMapping::Move>::Node*)':
    /usr/i686-w64-mingw32/include/qt/QtCore/qlist.h:493: undefined reference to `operator delete(void*)'

Any advice?

>Note that at least under Linux you do not need a debug build of Qt to debug your own code. I guess the same it true under Windows. So a debug build is only required for debugging Qt itself. But then you usually don't a packaged version and likely want the source code as well.

Qmake requires Qt libraries to have debugging symbols when compiling in debug mode, when compiling with MinGW.

**Comment by Martchus** [comment]
Ok, then I make it configurable via environment variable when I have to update the package anyways. I'll also add the patch for the correct name of the dbus library.

The error when compiling declarative probably occurs because it fails to link against the standard library. `libQt5QmlDevTools` is required by build tools which must run on the build machine and is therefore a Linux library despite cross compiling. The tricky thing is that it needs libs from `/usr/i686-w64-mingw32/lib` and from `/usr/lib`. But it also mustn't attempt to link against any Windows libraries in `/usr/i686-w64-mingw32/lib`.

To make this work I added the following hack to the PKGBUILD: https://github.com/Martchus/PKGBUILDs/blob/master/qt5-declarative/mingw-w64/PKGBUILD#L63

This "solution" is obviously not very reliable but I haven't found a better solution so far. But you can play around with the hack to make it work with your config. Without having the Makefiles generated at step https://github.com/Martchus/PKGBUILDs/blob/master/qt5-declarative/mingw-w64/PKGBUILD#L62 I can not help you with this.

> Qmake requires Qt libraries to have debugging symbols when compiling in debug mode, when compiling with MinGW.

Source? Why would using mingw-w64 make a difference for qmake regarding debug libraries?

**Comment by hipersayanX** [comment]
>This "solution" is obviously not very reliable but I haven't found a better solution so far.

At this point I just want any solution 😄 , thanks.

>Source? Why would using mingw-w64 make a difference for qmake regarding debug libraries?

When compiling in Qt Creator, it throw a lot of errors like this:

    686-w64-mingw32-g++ -g -shared -Wl,-subsystem,windows -mthreads -Wl,--out-implib,/home/user/webcamoid/libAvKys/Lib/libavkys.dll.a -o avkys.dll object_script.avkys.Debug  -lole32 -L/usr/i686-w64-mingw32/lib /usr/i686-w64-mingw32/lib/libQt5Guid.dll.a -lQt5Qmld /usr/i686-w64-mingw32/lib/libQt5Networkd.dll.a /usr/i686-w64-mingw32/lib/libQt5Cored.dll.a 
    /usr/lib/gcc/i686-w64-mingw32/6.3.1/../../../../i686-w64-mingw32/bin/ld: cannot find -lQt5Qmld

So instead of -lQt5Core, -lQt5Gui and so on, it try to find the debugging libraries with the **d** suffix, that is -lQt5Cored, -lQt5Guid.

**Comment by Martchus** [comment]
> When compiling in Qt Creator, it throw a lot of errors like this

Oh, and hence you can't compile the debug version of your own application. Got it. Requiring the debug version of Qt for building your own application with debug symbols seems to be the real issue here.

What happens if you just do a regular build? The `-g` flag should be added always and optimization will not prevent debugging. Just don't strip the binaries. If this doesn't work, you could still add the debug flags manually without telling the build system explicitly to do a debug build. Maybe we can also hack the build system to never append the *d* suffix. Or just create symlinks.

**Comment by hipersayanX** [comment]
>What happens if you just do a regular build?

Release mode is ok.

>you could still add the debug flags manually without telling the build system explicitly to do a debug build.

Gonna try that.

>Maybe we can also hack the build system to never append the d suffix. Or just create symlinks.

Official debugging binaries has the **d** suffix, so for compatibility the best option is the second one.

**Comment by hipersayanX** [comment]
Just added the symlinks for QtQmld, and get it working and debugging more or less. Not sure if closing this issue or if you want to continue working in this.

**Comment by Martchus** [comment]
Optionally enabling debug build of Qt itself is still a valid feature request so maybe I'll make it configurable via environment variable and let it find the dbus library. So I'll leave it open.

I also just tested the following to achieve a debug build:
```
$ i686-w64-mingw32-qmake-qt5 ..
$ make
i686-w64-mingw32-g++ -c -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions --param=ssp-buffer-size=4 -fno-keep-inline-dllexport -fpch-preprocess ...
make[1]: Verzeichnis „...“ wird verlassen
```
So the `-g` flag for debug symbols is present by default (as it is supposed to be). Hence there is really no need to do anything special to get a debug build. Just don't strip after all. This is also the case for building further Qt modules such as QML. So a solution for building a debug version of Qt declarative would be just to copy the libs appending the **d** suffix and then only strip the regular libs. Using this approach, a debug version of each further module (not included in base) could be implemented, too (without further messing the build system).

By the way, when building with CMake you also get debug symbols by default.

I'm also curious about your setup. So you debug natively under Windows or with Wine? Do you use any of https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=cross-mingw-w64-gdb and https://aur.archlinux.org/packages/mingw-w64-gdb?

**Comment by hipersayanX** [comment]
>So the -g flag for debug symbols is present by default (as it is supposed to be). 

You are right, I didn't noticed that. So the problem may be how Qmake resolve the path in debug mode.

>So you debug natively under Windows or with Wine? Do you use any of https://aur.archlinux.org/packages/cross-mingw-w64-gdb and https://aur.archlinux.org/packages/mingw-w64-gdb?

That's right, I configured Qt Creator to use your packages, and then I configure the project to use wineconsole as custom executable, wineconsole will then launch the program from a batch script as argument, the launcher is pretty similar to [this](https://github.com/webcamoid/webcamoid/blob/master/ports/deploy/windows/windowsdeploy.sh#L222), but using **echo off** and no **start /b ""**.

For debugging, I use a similar script, but launching the executable as:

    gdb -ex=r --args program.exe --other --arguments

I miss the integration with Qt Creator, but I can still debug it pretty much well. Also, you need to specify the paths for searching the required DLL.

    SET PATH=%cd%\other\paths;Z:\usr\i686-w64-mingw32\bin;%PATH%

**%cd%** will be replaced by the working directory that's configured in the project.

Once I have the program working, run the deploy script to generate the packages, and then I test the results in VirtualBox.

**Comment by Martchus** [comment]
Thanks for the info. I'll try it when I'm in the situation of having to debug again. So far I just used prints.

**Comment by Martchus** [comment]
Since there were enough other issues when updating to 5.9 I haven't had the time add a switch for debug build yet. However, the issue with the dbus lib should be fixed at least.

**Comment by Martchus** [comment]
Debug build can now be enabled by setting `MINGW_W64_QT_DEBUG_BUILD` in `/etc/makepkg.conf`.
