### ISSUE TITLE
issue compiling qtnetwork

### ISSUE THREAD

**Issue by drakkan** [Martchus/PKGBUILDs#32]
I tryed a new install in a clean chroot, the build now fails this way:

```
x86_64-w64-mingw32-g++ -g -shared -Wl,-subsystem,windows -Wl,--out-implib,/tmp/mingw-w64-qt5-base/src/build-x86_64-w64-mingw32/lib/libQt5Network.dll.a -o ../../lib/Qt5Network.dll object_script.Qt5Network.Release  -lws2_32 -lcrypt32 -ldnsapi -L/tmp/mingw-w64-qt5-base/src/build-x86_64-w64-mingw32/lib /tmp/mingw-w64-qt5-base/src/build-x86_64-w64-mingw32/lib/libQt5Core.dll.a -ldnsapi -liphlpapi -ladvapi32 -L/usr/x86_64-w64-mingw32/lib/openssl-1.0 -lssl -lcrypto -lcrypt32 -lz
./.obj/release/qsslsocket_openssl.o: In function `QWindowsCaRootFetcher::start()':
/tmp/mingw-w64-qt5-base/src/qtbase-opensource-src-5.9.0/src/network/ssl/qsslsocket_openssl.cpp:1390: undefined reference to `__imp_CertCreateCertificateContext'
/tmp/mingw-w64-qt5-base/src/qtbase-opensource-src-5.9.0/src/network/ssl/qsslsocket_openssl.cpp:1422: undefined reference to `__imp_CertGetCertificateChain'
/tmp/mingw-w64-qt5-base/src/qtbase-opensource-src-5.9.0/src/network/ssl/qsslsocket_openssl.cpp:1465: undefined reference to `__imp_CertFreeCertificateChain'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile.Release:503: ../../lib/Qt5Network.dll] Error 1
```

there is a small mistake in the PKGBUILD, here:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mingw-w64-qt5-base#n225

this line should be:

`export OPENSSL_LIBS="-L/usr/${_arch}/lib/openssl-1.0 -lssl -lcrypto"`

anyway this does not solves the linking issue, 

I have an old system (pre openssl 1.1) and I have no issue there,

I tryed to downgrade mingw toolchain to the previous one and I have the same error, 

so seems that the host openssl version influence the cross compilation, really strange. 

Are you able to compile in a full updated environment?

**Comment by Martchus** [comment]
> Are you able to compile in a full updated environment?

You can download https://martchus.no-ip.biz/repo/arch/ownstuff/os/x86_64/mingw-w64-qt5-base-5.9.0-1-x86_64.pkg.tar.xz from my binary repo. It should contain `.BUILDINFO` file with a list of all packages which were present at build time. Since then there were no relevant updates of mingw-w64 packages and regular openssl 1.1 has already been present as well. So yes, I guess I'm able to build.

> this line should be
Yes, it must be double quotes. But that mean that this line is actually not required because it builds here despite the mistake. So only the line above is actually required. This makes even sense because Qt Network loads OpenSSL dynamically at runtime and does not link against it at build time.

```
undefined reference to __imp_CertCreateCertificateContext' /tmp/mingw-w64-qt5-base/src/qtbase-opensource-src-5.9.0/src/network/ssl/qsslsocket_openssl.cpp:1422: undefined reference
```

My first guess would be that linker flag `-lcrypt32` is missing. However, the flag seems to be present in your invocation of g++.

Not sure why it is working in my case. Other users do not seem to have the problem, too. I'll investigate this.

```
/tmp/mingw-w64-qt5-base/src/build-x86_64-w64-mingw32/lib/libQt5Network.dll.a
```

This path doesn't look like you're building in a chroot at all. When using `makepkgchroot` everything is usually located under `/build`. Also note that building the package in tempfs is usually not a good idea as well because it is just too big.

**Comment by drakkan** [comment]
Thanks,

I'm building inside a clean virtual machine not in a chroot, I'm aware of the problem that I can have using tmpfs, in my case should be big enough,

I think compiling inside a chroot should not change anything, but if this is the preferred way I'll try.

Looking at your .BUILDINFO seems you have more or less the same environment as the one I'm using. 

Actually I tryed to disable openssl and the build succeded but I need ssl support in qtnetwork

**Comment by drakkan** [comment]
building in a clean chroot seems to solve the issue, this time I builded qt before any other package I need, really strange ...

**Comment by Martchus** [comment]
Ok, then I'll just remove wrong line when updating anyways.

To further investigate this, the installed packages in the error case would be required. However, I'm not sure whether it is worth it since using makechrootpkg is the recommended way of building anyways.
