### ISSUE TITLE
0018-Enable-rpath-for-build-tools.patch: QT_HOST_LIBS?

### ISSUE THREAD

**Issue by manisandro** [Martchus/PKGBUILDs#33]
On Fedora I need `$$[QT_HOST_LIBS]` instead of `$$[QT_INSTALL_LIBS/dev]` as rpath here [1] for the host tools since `$$[QT_INSTALL_LIBS/dev]` points to the target libdir (i.e. `/usr/i686-w64-mingw32/sys-root/mingw/lib`). Perhaps it is generally more correct to use `$$[QT_HOST_LIBS]`?

[1] https://github.com/Martchus/PKGBUILDs/blob/master/qt5-base/mingw-w64-angle/0018-Enable-rpath-for-build-tools.patch#L23

**Comment by Martchus** [comment]
I suppose under Arch Linux `$$[QT_INSTALL_LIBS/dev]` does not make much sense either. However, this value doesn't seem to have any effect. At least I'm getting the correct `rpath` anyways, eg.:

```
readelf -d /usr/bin/x86_64-w64-mingw32-qdoc-qt5 

Dynamic section at offset 0x119d70 contains 31 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libQt5QmlDevTools.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libQt5Bootstrap.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000f (RPATH)              Library rpath: [/usr/x86_64-w64-mingw32/lib]
...
```

Not sure whether removal of `CONFIG += relative_qt_rpath` is necessary, too. If not I better drop the entire patch.

Note that this patch is not from me, I've just re-based it. But I suppose the value `$$[QT_INSTALL_LIBS/dev]` for `QMAKE_RPATHDIR` comes from `qt.prf` where a similar assignment is done (see qtbase commit 967372c975fcaea5c2ef4e8a5950fb60bab10e6c). I don't know why this value was chosen for the rpath. The initial creator of the patch likely just copied it, too.

BTW: Since the previous maintainer of the Arch Linux package pulled a lot of patches from Fedora the initial creator might even be a Fedora developer.

**Comment by manisandro** [comment]
Hmm, possibly it was Erik van Pienbroek who sadly passed away (and I took over maintaining his packages). The patch definitely has an effect on Fedora, and with `$$[QT_HOST_LIBS]` it does the job:

    $ objdump -x /usr/i686-w64-mingw32/bin/qt5/moc  | grep RPATH
      RPATH                /usr/i686-w64-mingw32/lib

With `$$[QT_INSTALL_LIBS/dev]`, it failed to find `libQt5Bootstrap.so`, as indicated in the commit message of the patch.

**Comment by Martchus** [comment]
So the patch would be: https://github.com/Martchus/qtbase/commit/91af41300e9ee72ee369f506323695d9882371df.patch

This might break things under Arch, so I'll have to test first. Actually I guess this even will break things here because

> since $$[QT_INSTALL_LIBS/dev] points to the target libdir

If you are right and the variable points to the target libdir, this is exactly what I need under Arch because `libQt5Bootstrap.so` is in the target libdir under Arch which is `/usr/x86_64-w64-mingw32/lib`. The host directory would simply be `/usr/lib` here and can not contain `libQt5Bootstrap.so` because it would conflict with the regular Qt package. In the first place I thought this value has no effect anyways because I didn't see any rpath ending with `/dev` but `/dev` is likely part of the variable name.

**Comment by manisandro** [comment]
Ah, on Fedora we have `/usr/i686-w64-mingw32/lib/` for host and `/usr/i686-w64-mingw32/sys-root/mingw/lib` for target (and similar for `/usr/x86_64-w64-mingw32/`). The target dirs contain exclusively cross-compiled binaries.

**Comment by Martchus** [comment]
Having different special host dir for cross compiler packages is actually a good idea because then you don't have to put conflicting host libs in the target dir. However, I don't think this is going to be changed under Arch because only the Qt packages are affected by this simplification of the directory structure.

I can still test whether it actually break things here when rebuilding anyways. But it will likely not work under Arch so I'll likely have to keep the patch as it is.

**Comment by manisandro** [comment]
Ok no worries, I'll just add a comment to the spec to remind myself to adapt the patch when rebasing in the future.

**Comment by Martchus** [comment]
It didn't work.

BTW: Patches for 5.9.1 should be ready in a few days. I want to update Qt WebKit to ng version this time.

**Comment by manisandro** [comment]
Ok - I have 5.9.1 ready here [1], just waiting for some dependencies to get reviewed before importing into the main Fedora repos.

[1] https://copr.fedorainfracloud.org/coprs/smani/mingw-qt-5.9.1-testing/builds/
