### ISSUE TITLE
gogs: patches missing 1: default custom paths and ini file

### ISSUE THREAD

**Issue by mckaygerhard** [Martchus/PKGBUILDs#37]
i tested your great PKGBUILD and nothed the firs problem..

the systemd service and sysvinit scripts are not enough in certain cases,, to the daemon we must parse the config file...

or **patched the sources to use as default the** `/etc/gogs/app.ini` event the `custom/conf/app.ini`

**Comment by Martchus** [comment]
The systemd service file is actually patched to read the config from `/etc/gogs/app.ini`. So this does not work in your case? It is hard to understand the issue because your description is quite inaccurate.

**Comment by mckaygerhard** [comment]
umm i understand.. so i'll close this due you only support systemd.. so its only for my case due i adapt your PKGBUILD from my ARCH virtual machine to debian

my error was at the sysvinit script, for Devuan (debian fork that uses sysvinit) so close it

thanks, and sorry for my english always i write in a hurry...

**Comment by mckaygerhard** [comment]
hi! i'll change the title .. sorry i now eplain better

you only copy the default provided app.ini file.. so when go start .. event you said that ini file are customized to /etc/gogs/app.ini the rest of path are set to "custom" relative to gogs root, and the compilation assumes that gogs root install are /usr/bin!

i mean start by default it's not enought due in the /etc/gogs/app.ini file the settings are invalid (you only copy the default file to) and must only set changed settings..

**Comment by mckaygerhard** [comment]
also the ini file its just a copy with all setting same as default.. and must only have the changed settings.. 

so i recommend : 
1. create a empty file with only minimal needs (i'll provide that vaules at the end of that comment)
2. patched to use a different custom path.. the build assumed its under /usr/bin

```
APP_NAME = Gogs
RUN_USER = gogs
RUN_MODE = prod
 
[server]
PROTOCOL = http
DOMAIN = localhost
ROOT_URL = %(PROTOCOL)s://%(HTTP_ADDR)s:%(HTTP_PORT)s/
HTTP_ADDR = 0.0.0.0
HTTP_PORT = 3000
LOCAL_ROOT_URL = %(PROTOCOL)s://%(HTTP_ADDR)s:%(HTTP_PORT)s/
 
[repository]
ROOT = /var/lib/gogs/git
SCRIPT_TYPE = sh
DISABLE_HTTP_GIT = false
 
[database]
DB_TYPE = sqlite3
PATH = /var/lib/gogs/gogs.db
 
[session]
PROVIDER = file
 
[security]
INSTALL_LOCK = true
SECRET_KEY = ThisIsNotMySecretKey
```

**Comment by Martchus** [comment]
> umm i understand.. so i'll close this due you only support systemd.. so its only for my case due i adapt your PKGBUILD from my ARCH virtual machine to debian

Since Arch Linux only supports systemd (by default) this package only includes a service file for systemd. However, there might be alternative/additional packages to support other init systems, eg. [OpenRC](https://aur.archlinux.org/packages/gogs-openrc).

> also the ini file its just a copy with all setting same as default.. and must only have the changed settings

I'm aware that it is sufficient to provide a config file only containing the required changes. I already explained in an AUR comment, why I prefer to do otherwise:

> I guess upstream prefers having a custom config file containing only settings to be modified and hence include the 'DO NOT MODIFY' warning. I decided against that because I like to see all available options in the file, even if I mostly stick to the default value. Additionally, this approach prevents changed behavior in case the default changes. Instead, such changes are detected by pacman creating .pacnew/.pacsave file and it is easy to get a diff.

**Comment by mckaygerhard** [comment]
umm ok i understand.. 
so if only get minimal settings and let the rest totally commented...

and what about the changes i cited:

[server]
ROOT_URL = %(PROTOCOL)s://%(HTTP_ADDR)s:%(HTTP_PORT)s/

use the HTTP_ADDR (not very safe but enought to newbie users)

**Comment by Martchus** [comment]
Ok, in case a default value changes the behavior will change because unaltered values are actually only comments. What I meant it that I am aware of those changes because pacman will create a .pacnew/.pacsave file and it is easy to get a diff.

I only change the paths and the user because those values *must* be in accordance to the way the rest of the package is structured. I prefer to keep anything else as it is (intended by upstream).

**Comment by mckaygerhard** [comment]
umm some software may end in conflict when run in that behaviour.. 
but due gogs are not the case, everithing are good for that app.ini file

but still be be solved that gogs will not point to "custom/confg/app.ini" by default if where not run from daemon..  so a patch still are need

i think due the constant updates need to gogs its better run a "sed" command event made a patch

**Comment by Martchus** [comment]
If not running from daemon, one has to specify the path of the config file manually. I don't think it is worth the effort to improve this rare use case. If you really need to type the gogs command often and always want to use the config under /etc, just create a simple wrapper, a Bash alias, ...

I prefer to use patches instead of sed because patches actually complain when something changed and hence are more unlikely to unwanted changes. Rebasing the patches is quite easy thanks to Git, so I'll take the effort.

BTW: If you like to configure things differently than me, just create your own package (maybe using my version as base). I do the same with some other AUR packages. I really don't see the need to convince each other about anything.

**Comment by mckaygerhard** [comment]
umm ok so in that case i'll close this
