### ISSUE TITLE
gogs: bug - internal wiki does not show, got 500 error

### ISSUE THREAD

**Issue by mckaygerhard** [Martchus/PKGBUILDs#39]
ok fixed all the previously market and posted issues now.. this error only happened with a sync created repor (mirror repo type)

now when access the wiki got: 500 http error

log said:

```
2017/09/01 11:59:01 [TRACE] Session ID: be7cbd998cecfcd7
2017/09/01 11:59:01 [TRACE] CSRF Token: qx-hy0VjBpdwaUDJXw87VtQYKL86MTUwNDI3ODYxNDMwMjE0MzQ0MA==
2017/09/01 11:59:01 [ERROR] [.../routes/repo/wiki.go:53 renderWikiPage()] GetBranchCommit: object does not exist [id: refs/heads/master, rel_path: ]
2017/09/01 11:59:01 [TRACE] Template: status/500
```

seems need a wiki git repo internally.. or maybe setup into the app.ini.. later i'll report why or how!

**Comment by Martchus** [comment]
To summarize: Creating a Wiki (via the Gogs web UI) for a mirrored repository fails.

I haven't tested the mirroring feature myself yet. Looks like an upstream bug to me. You could check the Gogs project itself (or the Gitea fork) for related issues.

(BTW: I usually add Gogs as a second "remote for push" in my Git directories so Git pushes to GitHub and Gogs at the same time. I prefer having a truly independent instance instead of a mirror.)

**Comment by mckaygerhard** [comment]
it's a upstream bug.. i deeply tested and only happened with mirror repository: was reproduced at the try.gogs.io.. 
before i send i'll revise and check if there already other issue reported! should i let this open for users clarification or close it?

![error-wikimigrationbug-gogs](https://user-images.githubusercontent.com/1571724/29980069-0cc5d33a-8f16-11e7-9d11-e4a55d29d728.png)

**Comment by Martchus** [comment]
I would let it open until the issue is fixed. If you find or create a new upstream bug you can reference it here.

**Comment by mckaygerhard** [comment]
seems solved : https://github.com/gogits/gogs/issues/4464 but my sources was from lasted stable! but its not ! so i'll post a new issue at upstream

**Comment by mckaygerhard** [comment]
this problem was solved in gitea fork, now that i packaged gogs/gitea i recomended  the rest of the info i'll put at https://gitlab.com/venenux/venenux/blob/master/docs/PACKAGIN.git-gogs-gitea.md

**Comment by Martchus** [comment]
The info is not either English or German, so I'll not be able to look into it. But note that this repository also has (an untested) package for Gitea. However, I'll not switch myself to Gitea (or cherry-pick any Gitea commits) unless I run into any issues myself (never touch a running system). This issue is luckily not one of my use-cases. But thanks for the feedback, I'll keep it in mind.

**Comment by mckaygerhard** [comment]
well after many deep tests setups, gitea are more "exigent" rather than gogs, but better in features and others not fixed bugs ..

my package was based on your understand but now i'll changed to complaint to the oficial debian in near future..
