### ISSUE TITLE
mingw-w64-configure latest update is not in AUR

### ISSUE THREAD

**Issue by z3ntu** [Martchus/PKGBUILDs#43]
0.1-1 is the latest version in the AUR but 0.1-2 is in this repo and on the binary repo.
I know that you aren't the maintainer of the package in the AUR but maybe you can contact the maintainer and ask him to push the update?

Thanks for maintaining all these mingw-w64-* packages btw :)

**Comment by Martchus** [comment]
The idea of this change was to allow customizing flags via `CUSTOM_MINGW_FLAGS` variable. I also did the same for `mingw-w64-cmake`. This allows to get completely rid of the default flags proposed by those packages. I thought it would be useful to workaround some bugs which were present in the mingw-w64 tool-chain at this time.

However, it turned out that appending further flags is sufficient. Hence the change never made it into `mingw-w64-cmake` in the AUR and the version in my own repository should be identical to the 'official' AUR version as I did not merge my customization with further changes to the `mingw-w64-cmake` package. The same would be the case for `mingw-w64-configure` but there simply haven't been any further changes by the AUR maintainer.

So no reason to update the AUR package from my side. Since the `CUSTOM_MINGW_FLAGS` variable should not cause any trouble, no reason to rebuild the binary package, too.

---

BTW: I've noticed your aaurbs project. Seems to be inspired by aurbs from asdil. Do you use it for building mingw-w64 packages, too? I'm just asking because the version from asdil wasn't clever enough to do the job without causing too much rebuilds so I'm currently maintaining the binary repository manually (only with help of official devtools and some own scripts).

**Comment by z3ntu** [comment]
Okay thanks. Then maybe you could also provide the -1 version in your binary repo as it's a bit confusing that there's another version there than in the AUR.

About aaurbs: I actually turned off the build script on my server as I realised that it was 1. very insecure (literally executes everything thrown at it in the packages added) and 2. not very needed. I'm currently just using pacaur where I need it. If I ever touch it again, I will implement the verification of the PKGBUILD diffs (like pacaur does) and building afterwards in a secure and not too complicated way (the extra-x86_64-build script is not very nice for AUR especially with dependencies). And no, I have not heard of [aurbs](https://github.com/asdil12/aurbs) before. When I initially wrote it, that was a collection of simple bash scripts (found in the [legacy/ folder in the repo](https://github.com/z3ntu/aaurbs/tree/master/legacy)) that just built my packages. I then realised I needed a webinterface to add stuff and then it got more and more complicated. ^^

**Comment by Martchus** [comment]
A repository can only provide one version at a time and I'd rather stick to -2 to prevent warnings that the installed version is newer than the repository version. There is usually no way to 'go back'.

Different versions between the AUR and the binary repo can not be prevented in general anyways. Eg. if the AUR maintainer doesn't increase PKGREL when a rebuild is required I usually increase it myself. Or when the version of Git packages is automatically updated.

And thanks for the info about aaurbs.
