### ISSUE TITLE
Update apple-darwin-qt5-base

### ISSUE THREAD

**Issue by DragoonBoots** [Martchus/PKGBUILDs#52]
0004-Fix-build-errors-under-32-bit-MacOS.patch fails to apply with this output:

```
patching file src/plugins/platforms/cocoa/cocoa.pro
Hunk #1 succeeded at 118 (offset 14 lines).
patching file src/widgets/styles/styles.pri
Hunk #1 FAILED at 43.
1 out of 1 hunk FAILED -- saving rejects to file src/widgets/styles/styles.pri.rej
```

Looking at what the patch file is trying to do and comparing it to the current source for Qt's 5.10 branch ([here](https://github.com/qt/qtbase/blob/5.10/src/widgets/styles/styles.pri)) the file appears to have changed dramatically since the patch file was created.

**Comment by Martchus** [comment]
I'll continue to work on the apple-darwin packages soon. See https://github.com/Martchus/PKGBUILDs/issues/44.

---

About the *fail*: I would not have expected anything else since the Qt devs refactored the Qt Widgets styles (those are now plugins). I'll rebase when I continue to work on apple-darwin packages.

But I'll update the mingw-w64 ones first.

Note that the patches are managed on particular branches on my [fork](https://github.com/Martchus/qtbase). But as mentioned in https://github.com/Martchus/PKGBUILDs/issues/44, there are more basic things to fix about the apple-darwin packages first.

**Comment by DragoonBoots** [comment]
Noted; thanks for the great work so far!

**Comment by mridoni** [comment]
Hello, first of all congratulations on the great work. I understand how this may not be a priority, but is there any news on this? I tried today and the build stops due to the patches not being up to date (to get to this point I had to change the SHA256 hash in the PKGBUILD, otherwise the Qt archive fails the validation check).

Thanks

**Comment by Martchus** [comment]
There are no news, sorry. I only updated osxcross last year but I haven't tried to rebuild Qt against it. The only general improvement I made so far is generating the PKGBUILDs from a templates. This makes all the PKGBUILDs for extra repositories easier to maintain. But that's also not implemented for the `apple-darwin` versions yet.

**Comment by Martchus** [comment]
And about the validation check: At some point I accidentally updated the Qt version of the `apple-darwin` variants but haven't actually updated the rest of the PKGBUILDs. I never reverted the change because considering the problems which need to be resolved first there's not really a point in building them anyways.

**Comment by Martchus** [comment]
A few notes because I'm still receiving messages about these packages sometimes:

---

I've recently [reverted](https://github.com/Martchus/PKGBUILDs/commit/10bf32210df5360e7212f8da29e3e84f49e3dcee) the accidently updated `apple-darwin-qt5-*` packages to the last version I have actually been able to compile. Note that this version has been compiled against the version of osxcross which was the latest at the time I've created the `apple-darwin-qt5-*` packages and might not work with the updated version which is currently present. **However, I would not recommend to use it anyways because it showed problems at runtime.** Likely the problem is the use of libstdc++ instead of libc++.

---

I will not fix and update the `apple-darwin-qt5-*` packages anymore and instead wait for Qt 6. At this point it makes no sense to invest more time into the phased-out qmake-based build system. Maybe their switch to CMake makes things easier. But also don't expect me to work on the Qt 6 version anytime soon as I'll prioritize the mingw-w64 and Android packages.

**Comment by Martchus** [comment]
@jbliesener See my previous comment.

**Comment by jbliesener** [comment]
Thanks, standing by.

**Comment by mridoni** [comment]
I'll leave this here as a note/reminder for anybody who comes by and hasn't tried it: while it is not currently possible to build Qt5 with OsXCross, it is still possible to use it to build a Qt macOS program: you have to download and install Qt (I used 5.14.2) on a Mac, then move the relevant directories over to your machine (they don't need to be in OSxCross' tree). Obviously you' ll have to adjust your .pro files and or your makefiles with the proper include/library paths. In some cases, if possible, it will make more sense and be easier to make a custom build script or makefile and directly invoke moc/rcc (when needed). Assembling a bundle will also have to be done by hand, but after that the application will work without any problem (the usual caution applies here).
