### ISSUE TITLE
Add mingw-w64-hdf5

### ISSUE THREAD

**Issue by xantares** [Martchus/PKGBUILDs#65]
Hello,
Could mingw-w64-hdf5 package be added to your repo ?
xan.

**Comment by Martchus** [comment]
I can add it.

Since you're the maintainer of this package in the AUR I assume that you need to build this package anyways to check whether it builds successfully before uploading. In this case it would make sense to provide you a way to upload packages to my staging. This way we could save the effort to build the package twice.

**Comment by xantares** [comment]
I tried to build the mingw stack with wclang, but this does not succeed for all packages

**Comment by Martchus** [comment]
[When Clang compiles C++ code for Windows, it attempts to be compatible with MSVC.](https://clang.llvm.org/docs/MSVCCompatibility.html) Is this also the case when using wclang?

**Comment by xantares** [comment]
Yes I believe so, but I've not tried to link a real-world clang-built c++ lib with msvc.

**Comment by xantares** [comment]
I dont mind having to build it locally first.

**Comment by Martchus** [comment]
Depends on how much time I have :-)
