### ISSUE TITLE
Daylight savings not correctly applied in qml

### ISSUE THREAD

**Issue by jaytea** [Martchus/PKGBUILDs#67]
I stumbled upon a weird bug probably in these packages. The bug is explained in https://stackoverflow.com/questions/49942374/daylight-savings-not-applied-in-qml-in-windows-exe-compiled-with-mingw-w64.
When using another distro it works fine which leads me to believe that the problem lies somewhere in the packages here.

**Comment by Martchus** [comment]
> another distro

Which one exactly would be good to know? And I assume you're also referring to the mingw-w64 package provided by that distro?

Can you provide a small demo project to reproduce?

I assume you use the regular, dynamic version (`mingw-w64-qt5-base` package)?

**Comment by jaytea** [comment]
Sorry for the delay, I had a very busy weekend away from the PC.

> Which one exactly would be good to know? And I assume you're also referring to the mingw-w64 package provided by that distro?

I now use Ubuntu with MXE, which also uses mingw-w64.

> Can you provide a small demo project to reproduce?

I threw together a simple test qt-app:
[time_test.zip](https://github.com/Martchus/PKGBUILDs/files/1980933/time_test.zip)

> I assume you use the regular, dynamic version (mingw-w64-qt5-base package)?

Yes, you assume correctly.

**Comment by Martchus** [comment]
In my case this issue is different. At least when testing with Wine:  
![screenshot_20180507_221110](https://user-images.githubusercontent.com/10248953/39722585-8cf20286-5243-11e8-8e49-586d09a44708.png)

In the background is the correct value (native Linux build) and in the foreground the Windows version started with Wine. So the time and `Date.getHours()` are even correct, but in the timezone the daylight saving is also missing.

Hard to tell what's causing this. I can't find any patches in the [MXE](https://github.com/mxe/mxe/blob/master/src) which would fix this. I also doubt my own patches introduce any bugs regarding this. Yes, there are many patches, but most of them are about finding dependencies and other build system issues.

**Comment by jaytea** [comment]
That is weird with only the toString() being off. Though QDateTime also worked fine for me. So yeah, it is only a QML issue.
Interesting enough though, I once tried to supply the date through an interface into QML as a QDateTime and even then it had the same problem. So I would suspect the error being in the javascript engine and the Date type. 
I don't know if I have some time to dig deeper into this, but if I do I will let you know what I find.
Thanks for your help!
