### ISSUE TITLE
Update mingw-w64-mpv

### ISSUE THREAD

**Issue by NamedKitten** [Martchus/PKGBUILDs#78]
Please could you update MPV?

**Comment by Martchus** [comment]
I have almost forgotten that I have this package in the repository. I've only added it to test whether it works with ANGLE (and I believe it actually worked - at least dynamic linking). Though, I'm not sure whether to put more effort into the package at this point.

**Comment by NamedKitten** [comment]
It would be extremely handy for building https://github.com/NamedKitten/KittehPlayer
Which I would like to be added too if possible so I can make windows builds too.

Also heads up, your repo gives a error:
error: failed retrieving file 'mingw-w64-ffmpeg-1:4.0.2-1-any.pkg.tar.xz' from martchus.no-ip.biz : The requested URL returned error: 403
warning: failed to retrieve some files
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.

If we could do a static build of KittehPlayer on your packages then that would be great.
All KittehPlayer needs is qtquick* 5.11+ and MPV.

**Comment by NamedKitten** [comment]
KittehPlayer would also be a good test for MPV and Qt static ANGLE/whatever probably as well.

**Comment by Martchus** [comment]
I restricted the download intentionally because I used to built the package with libfdk_aac support (which would not legally distributable). However, since I'm not building with libfdk_aac support anymore, I removed the package from the blacklist. You should be able to download it now. And yes, ffmpeg must be updated, too.

> If we could do a static build of KittehPlayer on your packages then that would be great.

I remember that creating a static build of MPV didn't work because some libraries (or at least the linker flags) in the dependency chain where missing. That would have to be sorted out.

> Seems like just updating the MPV version makes it compile fine.

Go for a PR and maybe even send me the package if you like :-)

**Comment by Martchus** [comment]
I link your PR here: https://github.com/Martchus/PKGBUILDs/pull/79

> Seems like just updating the MPV version makes it compile fine.

I'm wondering how you've been able to build the static version. For me it complains that it can not find gmp which is indeed not available as static library. When I build a static version of gmp (using a hack to install it in the same prefix as the shared version) I get a lot of linker errors because the build system isn't able to pass all required linker flags in the correct order. Or did you just skip building the final `mpv.exe`?

**Comment by NamedKitten** [comment]
I usually just skip building mpv.exe.
Just add --disable-cplayer to the static configure for me.

**Comment by Martchus** [comment]
Ok. But when creating a static build of your own player you will have to sort out which transitive flags are required to link against static `libmpv` (beside `-lmpv`). Otherwise you will end up with the same errors you get when building `mpv.exe`. So it would be quite nice if the `mingw-w64-mpv` package would contain a `pkg-config` file with those flags already.

Closing the ticket, though.

**Comment by Martchus** [comment]
Just for the record, linking a static mpv or anything using libmpv does not work right now because:

* waf messes the (order of the) link flags or those are already incorrect in the pkg-config files of those libs
* gmp is only available as dynamic library (can be hacked around, but right now some static libs like nettle refer to the dynamic version)
* p11kit is only available as dynamic library (can likely also be hacked around)

Maybe it makes sense to build ffmpeg without gnutls to get rid of nettle and p11kit dependencies.

**Comment by NamedKitten** [comment]
shared libmpv works fine. To make the PKGBUILD work just don't build the static library and use --disable-cplayer to make mpv.exe not be built.

**Comment by NamedKitten** [comment]
But yeah I would recommend building ffmpeg without gnutls.
