### ISSUE TITLE
Unable to build mingw-w64-qt5-base

### ISSUE THREAD

**Issue by Verequies** [Martchus/PKGBUILDs#88]
Everytime I try to compile `mingw-w64-qt5-base`, the compilation fails with the below message. Oddly I'm able to compile `mingw-w64-qt5-base-static`.

`i686-w64-mingw32-g++ -Wl,-O1,--sort-common,--as-needed -shared -Wl,-subsystem,windows -Wl,--out-implib,/home/verequies/AUR/mingw-w64-qt5-base/src/build-i686-w64-mingw32/lib/libQt5Widgets.dll.a -o ../../lib/Qt5Widgets.dll @object_script.Qt5Widgets.Release  -L/home/verequies/AUR/mingw-w64-qt5-base/src/build-i686-w64-mingw32/lib /usr/i686-w64-mingw32/lib/libQt5Gui.dll.a /usr/i686-w64-mingw32/lib/libQt5Core.dll.a -lshell32 -luxtheme -ldwmapi -lopengl32 -lgdi32 -lcomdlg32 -loleaut32 -limm32 -lwinmm -lws2_32 -lole32 -luuid -luser32 -ladvapi32 -ljpeg -lpng -lharfbuzz -lfreetype /usr/i686-w64-mingw32/lib/libglu32.a /usr/i686-w64-mingw32/lib/libopengl32.a /usr/i686-w64-mingw32/lib/libgdi32.a /usr/i686-w64-mingw32/lib/libuser32.a 
/usr/lib/gcc/i686-w64-mingw32/8.2.0/../../../../i686-w64-mingw32/bin/ld: .obj/release/qapplication.o:qapplication.cpp:(.text+0xc729): undefined reference to '_imp___ZN22QGuiApplicationPrivate28sendApplicationPaletteChangeEbPKc'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile.Release:857: ../../lib/Qt5Widgets.dll] Error 1
make[3]: Leaving directory '/home/verequies/AUR/mingw-w64-qt5-base/src/build-i686-w64-mingw32/src/widgets'
make[2]: *** [Makefile:38: release] Error 2
make[2]: Leaving directory '/home/verequies/AUR/mingw-w64-qt5-base/src/build-i686-w64-mingw32/src/widgets'
make[1]: *** [Makefile:656: sub-widgets-make_first] Error 2
make[1]: Leaving directory '/home/verequies/AUR/mingw-w64-qt5-base/src/build-i686-w64-mingw32/src'
make: *** [Makefile:47: sub-src-make_first] Error 2
`

**Comment by Martchus** [comment]
It tries to link Qt Widgets against the installed version of Qt Core instead of the newly built version. This is a known problem. You need to uninstall the current version or preferably build everything in a clean chroot.

The static build obviously works because those libs are only archived but not linked. But to prevent any other issues there as well you should also build it in a clean environment and always with the matching version of the dynamic version.

BTW, this has been mentioned in the AUR comment section.

**Comment by Verequies** [comment]
@Martchus Not sure how I missed the comments on the AUR but yep it was said. Sorry my bad! All is compiling now :)

Thanks heaps!
