### ISSUE TITLE
Publish PKGBUILDs of *-git to AUR

### ISSUE THREAD

**Issue by yan12125** [Martchus/PKGBUILDs#99]
For example, I want to build syncthingtray-git with `SYNCTHING_TRAY_WEBVIEW_PROVIDER=none`. I can already do that by building from this repository, but I can't get updates for changes in PKGBUILD using common AUR helpers as they track AUR packages only. Could you consider publish at least c++utilities-git, qtutilities-git and syncthingtray-git to AUR? Thanks!

**Comment by Martchus** [comment]
I could do that but:

* Be aware that there might be no stable ABI during development versions of c++utilities and qtutilities. So you need to know when a new version of e.g. c++utilities requires a rebuild of qtutilities and syncthingtray.
* I would upload that PKGBUILDs once and only change them when a change is required. There is usually no new PKGBUILD for every commit in Git packages and my Git packages wouldn't be an exception. So unless your AUR helper provides something fancy here you would still not be notified about new commits.

So you really don't like that dependency? Because otherwise the internal webview can just be disabled.

**Comment by Martchus** [comment]
I nevertheless submitted the PKGBUILDs to the AUR.

**Comment by yan12125** [comment]
> There is usually no new PKGBUILD for every commit in Git packages and my Git packages wouldn't be an exception.

I use [lilac](https://github.com/archlinuxcn/lilac/), which can track both PKGBUILDs on AUR and git repos. Popular AUR helpers like [yay](https://github.com/Jguer/yay) has `--devel` as well.

> Be aware that there might be no stable ABI during development versions of c++utilities and qtutilities.

Yep that might be a problem. Fortunately with name mangling, most ABI changes are visible at binding time.

> So you really don't like that dependency? Because otherwise the internal webview can just be disabled.

Just my religious belief - I tend to avoid more than one copies of browser engines on my machine.

> I nevertheless submitted the PKGBUILDs to the AUR.

Thanks!

**Comment by Martchus** [comment]
Ok, good to know. I'm using just some self-crafted scripts for providing my binary repo.

I'm also not a big fan of having too many browser engines around. Qt WebEngine is shared by various applications which I'm using so it is ok-ish. I'm still reluctant to distribute Qt WebEngine for the Windows version and of course there will always be a "no webview" switch in my applications.

**Comment by yan12125** [comment]
> there will always be a "no webview" switch in my applications.

That's good :)
